### ISSUE TITLE
Installation / usage issue - "FileNotFoundError: [WinError 2] The system cannot find the file specified"

### ISSUE THREAD

**Issue by KodeAron** [eiphy/conda-export#1]
Have a difficult time figuring out how to install this. And how to use it. Not much info in the readme. Yes, I am new to this (installing packages from github).

I found out the package is added in pip, so I tried to simply run `pip install ecoport`, inside the conda environment. It seem to work. Kind of. I get the files. It shows up in C:\ProgramData\Anaconda3\envs\myenv\Lib\site-packages. 

However, when I try to run `python -m ecoport` I get a FileNotFoundError.

I tried to install it in base and there it worked. But, there is not really any point using this if I can't run it in different environments.

```
(myenv) C:\ws>pip install ecoport
Requirement already satisfied: ecoport in c:\programdata\anaconda3\envs\myenv\lib\site-packages (0.0.1)
Requirement already satisfied: pyyaml in c:\programdata\anaconda3\envs\myenv\lib\site-packages (from ecoport) (6.0)

(myenv) C:\ws>python -m ecoport
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\myenv\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Anaconda3\envs\myenv\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\myenv\lib\site-packages\ecoport\__main__.py", line 83, in <module>
    main(args)
  File "C:\ProgramData\Anaconda3\envs\myenv\lib\site-packages\ecoport\__main__.py", line 59, in main
    pkg_names = [n for n in get_history_export_pkg_names()]
  File "C:\ProgramData\Anaconda3\envs\myenv\lib\site-packages\ecoport\__main__.py", line 40, in get_history_export_pkg_names
    subprocess.check_output("conda env export --from-history".split(" "))
  File "C:\ProgramData\Anaconda3\envs\myenv\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\ProgramData\Anaconda3\envs\myenv\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\ProgramData\Anaconda3\envs\myenv\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\ProgramData\Anaconda3\envs\myenv\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by eiphy** [comment]
Hi @CodeAron, sorry for the late reply. I think your problem might be related to https://discuss.python.org/t/filenotfounderror-winerror-2-the-system-cannot-find-the-file-specified/9757/11

However, I cannot reproduce your problem in both CMD and anaconda shell (I assume you are using windows).

Can you try to run `conda env export --from-history` in your shell? If you are able to run it, then we are sure the problem is the subprocess module. And can add `shell=True` to the source code.

In addition, feel free to clone the repo and install it in editable mode (see the README in dev branch) and test the `shell=True` (add in the subprocess.check_output method) option.

Let me know if you need more help.

Thank you.
